
package collaborateur.web.service.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "CollaborateurInconnuException", targetNamespace = "http://services.model.service.web.collaborateur/")
public class CollaborateurInconnuException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CollaborateurInconnuException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public CollaborateurInconnuException_Exception(String message, CollaborateurInconnuException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public CollaborateurInconnuException_Exception(String message, CollaborateurInconnuException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: collaborateur.web.service.client.CollaborateurInconnuException
     */
    public CollaborateurInconnuException getFaultInfo() {
        return faultInfo;
    }

}
