
package collaborateur.web.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CollaborateurServiceImplService", targetNamespace = "http://services.model.service.web.collaborateur/", wsdlLocation = "http://localhost:8478/collaborateurService?wsdl")
public class CollaborateurServiceImplService
    extends Service
{

    private final static URL COLLABORATEURSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException COLLABORATEURSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName COLLABORATEURSERVICEIMPLSERVICE_QNAME = new QName("http://services.model.service.web.collaborateur/", "CollaborateurServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8478/collaborateurService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COLLABORATEURSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        COLLABORATEURSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CollaborateurServiceImplService() {
        super(__getWsdlLocation(), COLLABORATEURSERVICEIMPLSERVICE_QNAME);
    }

    public CollaborateurServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COLLABORATEURSERVICEIMPLSERVICE_QNAME, features);
    }

    public CollaborateurServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, COLLABORATEURSERVICEIMPLSERVICE_QNAME);
    }

    public CollaborateurServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COLLABORATEURSERVICEIMPLSERVICE_QNAME, features);
    }

    public CollaborateurServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CollaborateurServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CollaborateurService
     */
    @WebEndpoint(name = "CollaborateurServiceImplPort")
    public CollaborateurService getCollaborateurServiceImplPort() {
        return super.getPort(new QName("http://services.model.service.web.collaborateur/", "CollaborateurServiceImplPort"), CollaborateurService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollaborateurService
     */
    @WebEndpoint(name = "CollaborateurServiceImplPort")
    public CollaborateurService getCollaborateurServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.model.service.web.collaborateur/", "CollaborateurServiceImplPort"), CollaborateurService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COLLABORATEURSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw COLLABORATEURSERVICEIMPLSERVICE_EXCEPTION;
        }
        return COLLABORATEURSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
